name: Build Windows

on:
  release:
    types: [created]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.5.3'

    - name: Install dependencies
      run: flutter pub get
      working-directory: ./Scout-Ops-Android

    - name: Build Windows
      run: flutter build windows
      working-directory: ./Scout-Ops-Android

    - name: Create MSIX package
      run: dart run msix:create
      working-directory: ./Scout-Ops-Android

    - name: Upload Windows build
      run: zip -r windows-build.zip ./Scout-Ops-Android/build/windows

    - name: Upload Windows build to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./Scout-Ops-Android/build/windows
        asset_name: windows-build.zip
        asset_content_type: application/zip
