name: Build Android

on:
  release:
    types: [created]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.5.3'

    - name: Install dependencies
      run: flutter pub get
      working-directory: ./Scout-Ops-Android

    - name: Build APK
      run: flutter build apk --release
      working-directory: ./Scout-Ops-Android

    - name: Upload APK
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./Scout-Ops-Android/build/app/outputs/flutter-apk/app-release.apk
        asset_name: app-release.apk
        asset_content_type: application/vnd.android.package-archive
