name: Build Web

on:
  release:
    types: [created]

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.5.3'

    - name: Install dependencies
      run: flutter pub get
      working-directory: ./Scout-Ops-Android

    - name: Build Web
      run: flutter build web
      working-directory: ./Scout-Ops-Android

    - name: Upload Web build
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./Scout-Ops-Android/build/web
        asset_name: web-build.zip
        asset_content_type: application/zip
      run: zip -r web-build.zip ./Scout-Ops-Android/build/web
