name: Generate Assets

on:
  release:
    types: [created]

jobs:
  build-android:
    uses: ./.github/workflows/build-android.yml

  build-web:
    needs: build-android
    uses: ./.github/workflows/build-web.yml

  build-windows:
    needs: build-web
    uses: ./.github/workflows/build-windows.yml
